name: 'Virtuoso sparql'
author: Yann POMIE
branding:
  color: blue
  icon: database
description: 'Spawn a virtuoso instace and fill it with data!'

inputs:
  dba-password:
    description: 'ENV variable DBA_PASSWORD. Default: password'
    required: false
    default: 'password'
  dav-password:
    description: 'ENV variable DAV_PASSWORD. Default: password'
    required: false
    default: 'password'
  triples:
    description: 'Files and and directories to import triples from, supports CSV'
    required: false
    default: ''
  publish-db-port:
    description: "Publish database's port to host. Default: 1111"
    required: false
    default: '1111'
  publish-http-server-port:
    description: "Publish HTTP server's port to host, and thus the endpoint /sparql. Default: 8890"
    required: false
    default: '8890'

runs:
  using: 'node16'
  main: './dist/index.js'