name: Release

on:
  push:
    tags: 
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup node js
      uses: actions/setup-node@v3.2.0
    - run: npm i
    - run: npm run build

    - name: Publish to Marketplace
      uses: ncipollo/release-action@v1.10.0
      with:
        name: Sparql Virtuoso action ${{ github.ref_name }}
        tag:  ${{ github.ref_name }}
        omitBody: true
