#use this alongside act to test the cd locally
name: Release
on:
  push:
    branches: [ master, cicd ]
    tags: 
      - release[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup node js
      uses: actions/setup-node@v3.2.0
    - run: npm i
    - run: npm run build

    - name: Set Versions
      uses: actions/github-script@v4
      id: set_version
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const tag = context.ref.substring(10)
          const with_v = tag.replace('release', 'v')
          core.setOutput('with_v', with_v)

    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.14.1
      id: git_commit
      with:
        branch: master
        file_pattern: ./dist*
        commit_message: git commit -sm ${{ steps.set_version.outputs.with_v }}" [skip ci]"
        commit_author: WoodenMaiden <yann.pomie@laposte.net>
        commit_user_name: Action (automated)
        commit_user_email: yann.pomie@laposte.net
        tagging_message: ${{ steps.set_version.outputs.with_v }}

    - run : git log --oneline ${{ steps.git_commit.outputs.commit_hash }} | cat