#use this alongside act to test the action locally
name: Tests
on:
  push:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup node js
      uses: actions/setup-node@v3.2.0

    - run: npm i
    
    - name: Start a Virtuoso instance and fill it
      uses: ./
      with:
        dba-password: PASSWORD1
        dav-password: PASSWORD
        publish-db-port: 2222
        publish-http-server-port: 8888
        triples: ./test_dataset.ttl